// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr4JH2M__PRymOCHlJFa5kMw_-helfTX4',
    appId: '1:707413609534:web:68ef9d8d2178b73f9a156f',
    messagingSenderId: '707413609534',
    projectId: 'nextstep-us-2026',
    authDomain: 'nextstep-us-2026.firebaseapp.com',
    storageBucket: 'nextstep-us-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTs_7YFc8QCkaOnIWjNly9d7OxxklEL0',
    appId: '1:707413609534:android:67bb35819be0cfad9a156f',
    messagingSenderId: '707413609534',
    projectId: 'nextstep-us-2026',
    storageBucket: 'nextstep-us-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdjNEbAgiCb9cvVmlnVbi8FMYDct5NVp0',
    appId: '1:707413609534:ios:f00b1c532ddad6fc9a156f',
    messagingSenderId: '707413609534',
    projectId: 'nextstep-us-2026',
    storageBucket: 'nextstep-us-2026.firebasestorage.app',
    iosBundleId: 'com.example.nextstep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdjNEbAgiCb9cvVmlnVbi8FMYDct5NVp0',
    appId: '1:707413609534:ios:f00b1c532ddad6fc9a156f',
    messagingSenderId: '707413609534',
    projectId: 'nextstep-us-2026',
    storageBucket: 'nextstep-us-2026.firebasestorage.app',
    iosBundleId: 'com.example.nextstep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr4JH2M__PRymOCHlJFa5kMw_-helfTX4',
    appId: '1:707413609534:web:7597dc885d33c46a9a156f',
    messagingSenderId: '707413609534',
    projectId: 'nextstep-us-2026',
    authDomain: 'nextstep-us-2026.firebaseapp.com',
    storageBucket: 'nextstep-us-2026.firebasestorage.app',
  );

}